name: Greeting from Cheung Ka Ho
on: push
 
jobs:
 my-jobs:
   name: My Job
   runs-on: ubuntu-latest
   steps:
   - name: Print a Greeting
     env:
       MY_VAR: Hi there! My name is
       FIRST_NAME: Cheung
       MIDDLE_NAME: Ka
       LAST_NAME: Ho
     run: |
       echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
